# Generated by Django 4.2 on 2023-04-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('max_temp', models.IntegerField()),
                ('min_temp', models.IntegerField()),
                ('precipitation', models.IntegerField()),
            ],
        ),
    ]
