# Generated by Django 4.2 on 2023-04-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherstats',
            name='avg_max_temp',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='weatherstats',
            name='avg_min_temp',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='weatherstats',
            name='total_precipitation',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
